In [39]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [40]:
data = pd.read_csv("homeprices.csv")
data.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [41]:
data =pd.get_dummies(data, drop_first=True)
data.head()

   area   price  town_robinsville  town_west windsor
0  2600  550000                 0                  0
1  3000  565000                 0                  0
2  3200  610000                 0                  0
3  3600  680000                 0                  0
4  4000  725000                 0                  0

In [42]:
X = data.drop('price', axis='columns')
X.head()

   area  town_robinsville  town_west windsor
0  2600                 0                  0
1  3000                 0                  0
2  3200                 0                  0
3  3600                 0                  0
4  4000                 0                  0

In [43]:
Y=data.price
Y.head()

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [44]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression

In [45]:
lr.fit(X, Y )

TypeError: fit() missing 1 required positional argument: 'y'

In [ ]:
X.head()

   area  town_robinsville  town_west windsor
0  2600                 0                  0
1  3000                 0                  0
2  3200                 0                  0
3  3600                 0                  0
4  4000                 0                  0

In [ ]:
lr.predict([[3000, 3, 1, 0]])

TypeError: predict() missing 1 required positional argument: 'X'

In [ ]:
lr.predict([[3000, 3, 1, 0]])n

TypeError: predict() missing 1 required positional argument: 'X'

In [46]:
data = pd.read_csv("homeprices.csv")
data.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [49]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [50]:
encoded_data = encoder.fit_transform(data[['town']]).toarray()
encoded_data

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [53]:
column_names = encoder.get_feature_names_out(['town'])
encoder_df = pd.DataFrame(encoder_data, columns=column_names)
encoder_df

AttributeError: 'OneHotEncoder' object has no attribute 'get_feature_names_out'

AttributeError: 'OneHotEncoder' object has no attribute 'get_feature_names_out'

In [57]:
final_df = pd.concat([data[['area','price']], encoder_df], axis=1)
final_df.head()

NameError: name 'encoder_df' is not defined