In [1]:
import pandas as pd 
pd.__version__

'1.2.4'

In [5]:
ser = pd.Series([10,20,30,40],index = ['a','b','c','d'])
ser

a    10
b    20
c    30
d    40
dtype: int64

In [6]:
import numpy as np

In [7]:
data = np.random.randint(1,20,size=20).reshape(5,4)
data

array([[15, 13, 17, 15],
       [ 4,  6,  4,  5],
       [15, 13, 19, 14],
       [16,  4,  8,  2],
       [ 6,  9, 13, 16]])

In [8]:
df = pd.DataFrame(data,index=['a','b','c','d','e'],columns=['A','B','C','D'])
df

    A   B   C   D
a  15  13  17  15
b   4   6   4   5
c  15  13  19  14
d  16   4   8   2
e   6   9  13  16

In [9]:
df['B']

a    13
b     6
c    13
d     4
e     9
Name: B, dtype: int32

In [11]:
df[['A','C']]

    A   C
a  15  17
b   4   4
c  15  19
d  16   8
e   6  13

In [12]:
df.loc["a"]

A    15
B    13
C    17
D    15
Name: a, dtype: int32

In [17]:
df.loc[["a","b"]]

    A   B   C   D
a  15  13  17  15
b   4   6   4   5

In [28]:
data = {
    "Name": ["Sahithi", "sai", "yavanika", "lasya", "akhila"],
    "Age": [19, 20, 19, 40, 45],
    "City": ["vizag", "Los Angeles", "Chicago", "Houston", "Phoenix"],
    "Qualification": ["B.Tech", "M.Tech", "PhD", "MSc", "BSc"]
}

In [29]:
df = pd.DataFrame(data, index=["A","B","C","D","E"])
df

       Name  Age         City Qualification
A   Sahithi   19        vizag        B.Tech
B       sai   20  Los Angeles        M.Tech
C  yavanika   19      Chicago           PhD
D     lasya   40      Houston           MSc
E    akhila   45      Phoenix           BSc

In [31]:
data = pd.read_csv("data.csv")
data.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0